### ISSUE TITLE
Question: IOError

### ISSUE THREAD

**Issue by ysm0128** [AshleyLab/stmp#1]
Hi,
I'm interested in STMP and want to run STMP. 
Whenever I try to run STMP on an input VCF, an error occurs.
I have been trying to figure our what is causing the error I am getting, but I can't get my issue.

Here is my code.

[ysm0128@piano STMP]$ python ./stmp-1.0.0/code/stmp.py --vcf==/storage/home/ysm0128/download/annovar/example/ex2.vcf --output_dir=output
using database file: /storage/home/ysm0128/download/STMP/stmp-1.0.0/db/annotationDB.sqlite
Converting VCF so there is only 1 allele per line
[main] Unrecognized command.
Stripping chr prefix from VCF CHROM column (if present)
Traceback (most recent call last):
  File "./stmp-1.0.0/code/stmp.py", line 175, in <module>
    stripChr_vcf = stmp_annotation_util.stripChrPrefix(args.vcf, args.scratch_dir, skip_if_exists=False)
  File "/storage/home/ysm0128/download/STMP/stmp-1.0.0/code/stmp_annotation_util.py", line 174, in stripChrPrefix
    vcf = open_compressed_or_regular(vcf_filepath, 'r')
  File "/storage/home/ysm0128/download/STMP/stmp-1.0.0/code/stmp_annotation_util.py", line 52, in open_compressed_or_regular
    return gzip.open(f, options)
  File "/usr/lib64/python2.6/gzip.py", line 33, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib64/python2.6/gzip.py", line 79, in **init**
    fileobj = self.myfileobj = **builtin**.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/storage/home/ysm0128/download/STMP/output/scratch/ex2_noMultiallelic.vcf.gz'

I have confirmed that the folder and file do exist. What is causing the IOError and how to I resolve it?

**Comment by thesyntaxinator** [comment]
It looks like you have "==" instead of "=" after the vcf parameter. Could you try it with just one equals sign? (e.g. python ./stmp-1.0.0/code/stmp.py --vcf=/storage/home/ysm0128/download/annovar/example/ex2.vcf --output_dir=output)

**Comment by ysm0128** [comment]
Thank you for answering.
However, I also have the same error message when I try it with "=" again.

using database file: /storage/home/ysm0128/download/STMP/stmp-1.0.0/db/annotationDB.sqlite
Converting VCF so there is only 1 allele per line
[main] Unrecognized command.
Stripping chr prefix from VCF CHROM column (if present)
Traceback (most recent call last):
  File "./stmp-1.0.0/code/stmp.py", line 175, in <module>
    stripChr_vcf = stmp_annotation_util.stripChrPrefix(args.vcf, args.scratch_dir, skip_if_exists=False)
  File "/storage/home/ysm0128/download/STMP/stmp-1.0.0/code/stmp_annotation_util.py", line 174, in stripChrPrefix
    vcf = open_compressed_or_regular(vcf_filepath, 'r')
  File "/storage/home/ysm0128/download/STMP/stmp-1.0.0/code/stmp_annotation_util.py", line 52, in open_compressed_or_regular
    return gzip.open(f, options)
  File "/usr/lib64/python2.6/gzip.py", line 33, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib64/python2.6/gzip.py", line 79, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/storage/home/ysm0128/download/STMP/output/scratch/ex2_noMultiallelic.vcf.gz'

How can I sole the problem?

**Comment by thesyntaxinator** [comment]
Can you paste the command you used? I can test it on my end.

**Comment by ysm0128** [comment]
This is my code.
 
python ./stmp-1.0.0/code/stmp.py --vcf=input/ex2.vcf --output_dir=output 

The vcf file is from annovar.
